//! Interactive element gallery for the browser.
//!
//! This is a separate workspace crate, not a feature of `svg-dom` itself: it depends on `svg-dom` the same way any
//! external consumer would (a plain `Cargo.toml` path dependency), reaching it only through its public API. This
//! keeps the demo gallery's build out of the main library's own dependency graph and — since a private/internal
//! item this crate accidentally relied on would simply fail to compile — doubles as a standing check that the
//! library's public surface is actually sufficient to build a real, full-featured application against.
//!
//! Build and serve with:
//! ```sh
//! cargo demo
//! ```
//! which rebuilds this crate's wasm package and serves it via the Actix `demo-server` crate at
//! <http://127.0.0.1:8080/demo/>.

mod colours;
mod events;
mod geometry;
mod highlight;
mod paint;
mod shapes;
mod structure;
mod texts;

use std::{cell::RefCell, rc::Rc};
use svg_dom::{AnimationLoop, CachedAttr, Error, SvgAttrs, SvgNode, SvgRoot, root::utils::Point};
use wasm_bindgen::prelude::*;

use colours::*;

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
thread_local! {
    /// Demo-only owner for interactive nodes whose managed listeners must remain attached after the demo function
    /// that created them returns.
    ///
    /// The library intentionally removes a DOM listener when the last `SvgNode` handle is dropped.  Browser demos are
    /// long-lived, so they keep listener-owning nodes here instead of leaking individual `Closure`s.
    static LIVE_DEMO_NODES: RefCell<Vec<SvgNode>> = const { RefCell::new(Vec::new()) };

    /// Demo-only owner for every running `AnimationLoop`.
    ///
    /// `AnimationLoop` stops on `Drop`, so each demo parks its loop here to keep it running for the page's lifetime.
    /// This has to be a collection, not a single slot: more than one demo (`structure::demo_anim` and
    /// `geometry::demo_geometry_path_follow`) runs its own independent `AnimationLoop`, and a single `Option` slot
    /// would let the second call silently drop and stop the first one's animation.
    static LIVE_DEMO_ANIMS: RefCell<Vec<AnimationLoop>> = const { RefCell::new(Vec::new()) };
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
fn keep_demo_node(node: SvgNode) {
    LIVE_DEMO_NODES.with(|nodes| nodes.borrow_mut().push(node));
}

fn keep_demo_anim(anim: AnimationLoop) {
    LIVE_DEMO_ANIMS.with(|anims| anims.borrow_mut().push(anim));
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Event-type-generic handler that routes a constant `last: {name}` label through a shared `CachedAttr`, so a burst of
// identical labels (a stream of pointermove/touchmove events) skips the DOM write after the first. Every writer to a
// given readout must share the *same* cache for it to stay coherent.
fn cached_label<E>(readout: SvgNode, cache: Rc<RefCell<CachedAttr>>, name: &'static str) -> impl Fn(E) + 'static {
    // The label is constant; format it once so the cached write is fully allocation-free per event.
    let label = format!("last: {name}");
    move |_| {
        let _ = cache.borrow_mut().set_text(&readout, &label);
    }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Constants
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Single source of truth for the demo canvas dimensions. `create_in` writes these to each <svg>'s width/height
// attributes, which size the rendered element — so style.css deliberately does not repeat them.
const W: f64 = 800.0; // SVG width shared across all demo canvases
const H: f64 = 180.0; // SVG height shared across all demo canvases

// The demos are composed within a BAND-tall region. PAD_Y is the offset that vertically centres that band in the
// canvas, so every demo's content stays in the middle whatever H is. (PAD_Y is 0 when H == BAND.)
const BAND: f64 = 130.0;
const PAD_Y: f64 = (H - BAND) / 2.0;

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Panel registry (DEMO_PANELS, generated below by demo_gallery!) and the lazy per-panel entry point that uses it
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

/// All demo sub-module sources concatenated at build time so each panel can display the exact code that drives it.
/// Placed here, above [`demo_gallery`], because [`demo_fn_source`] needs it and macros expand in place: `DEMO_PANELS`,
/// generated by the invocation below, only sees items already declared lexically above it in this file.
const DEMO_SRC: &str = concat!(
    include_str!("shapes.rs"),
    include_str!("texts.rs"),
    include_str!("structure.rs"),
    include_str!("paint.rs"),
    include_str!("events.rs"),
    include_str!("geometry.rs"),
);

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Generates [`DEMO_PANELS`] from one list, so a panel's id, its build function, and the function name shown in its
/// source frame can never drift apart the way three independently hand-maintained lists could.
///
/// This file's own module-grouped order (shapes, then structure, then paint, ...) is what `DEMO_PANELS` ends up in.
/// That no longer means anything operationally — every panel is looked up by id via [`init_panel`], not iterated in
/// order — and it is not, and has no need to be, the menu's category order. The menu is built separately, from
/// `demo-server`'s own manifest (`demo-server/src/panels.rs`); the two lists serve different purposes and have no
/// reason to match.
macro_rules! demo_gallery {
    ( $( $panel_id:literal => $module:ident :: $func:ident ),+ $(,)? ) => {
        /// `(panel id, demo build function, demo function name)` for every demo, generated by the `demo_gallery!`
        /// invocation below. [`init_panel`] looks a panel up here by id to build it the first time it is selected;
        /// the function name is what [`demo_fn_source`] looks up in [`DEMO_SRC`] to display alongside it.
        const DEMO_PANELS: &[(&str, fn() -> Result<(), Error>, &str)] = &[
            $( ($panel_id, $module::$func, stringify!($func)) ),+
        ];
    };
}

demo_gallery! {
    "panel-rect" => shapes::demo_rect,
    "panel-circle" => shapes::demo_circle,
    "panel-ellipse" => shapes::demo_ellipse,
    "panel-line" => shapes::demo_line,
    "panel-poly" => shapes::demo_poly,
    "panel-path" => shapes::demo_path,
    "panel-text" => texts::demo_text,
    "panel-group" => structure::demo_group,
    "panel-anim" => structure::demo_anim,
    "panel-marker" => structure::demo_marker,
    "panel-marker-view-box" => structure::demo_marker_view_box,
    "panel-use" => structure::demo_use,
    "panel-image" => structure::demo_image,
    "panel-symbol" => structure::demo_symbol,
    "panel-anchor" => structure::demo_anchor,
    "panel-switch" => structure::demo_switch,
    "panel-view" => structure::demo_view,
    "panel-style" => structure::demo_style,
    "panel-foreign-object" => structure::demo_foreign_object,
    "panel-view-box" => structure::demo_view_box,
    "panel-tree-nav" => structure::demo_tree_nav,
    "panel-accessibility" => structure::demo_accessibility,
    "panel-linear-gradient" => paint::demo_linear_gradient,
    "panel-radial-gradient" => paint::demo_radial_gradient,
    "panel-clip-path" => paint::demo_clip_path,
    "panel-mask" => paint::demo_mask,
    "panel-pattern" => paint::demo_pattern,
    "panel-filter" => paint::demo_filter,
    "panel-color-matrix" => paint::demo_color_matrix,
    "panel-blend" => paint::demo_blend,
    "panel-component-transfer" => paint::demo_component_transfer,
    "panel-turbulence" => paint::demo_turbulence,
    "panel-morphology" => paint::demo_morphology,
    "panel-fe-image" => paint::demo_fe_image,
    "panel-fe-tile" => paint::demo_fe_tile,
    "panel-convolve-matrix" => paint::demo_convolve_matrix,
    "panel-lighting" => paint::demo_lighting,
    "panel-light-sources" => paint::demo_light_sources,
    "panel-tspan" => texts::demo_tspan,
    "panel-text-path" => texts::demo_text_path,
    "panel-events-click" => events::demo_events_click,
    "panel-events-colour" => events::demo_events_colour,
    "panel-events-modifiers" => events::demo_events_modifiers,
    "panel-events-press" => events::demo_events_press,
    "panel-events-group" => events::demo_events_group,
    "panel-events-pointer" => events::demo_events_pointer_lifecycle,
    "panel-events-keyboard-wheel" => events::demo_events_keyboard_wheel,
    "panel-events-drag-drop-touch" => events::demo_events_drag_drop_touch,
    "panel-events-passive" => events::demo_events_passive,
    "panel-events-classlist" => events::demo_events_classlist,
    "panel-geometry-path-follow" => geometry::demo_geometry_path_follow,
    "panel-geometry-bbox" => geometry::demo_geometry_bounding_box,
}

/// Marks a panel's `<section>` with its initialisation outcome, so [`init_panel`] can tell "never attempted"
/// (attribute absent) apart from "already attempted" (attribute present, `"ready"` or `"failed"`) and skip
/// rebuilding a panel that has already been built once — rebuilding it again would duplicate its contents rather
/// than replace them, since `SvgRoot::create_in` always appends a fresh `<svg>` into the canvas `<div>`.
const PANEL_STATE_ATTR: &str = "data-panel-state";

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Builds one demo panel's content the first time it is selected, rather than every panel eagerly at page load —
/// which is what this gallery used to do, even though at most one panel is ever visible at once (every other
/// `<section>` sits behind `display: none`; see `.section`/`.section.active` in `style.css`). That eager approach
/// meant, among other costs, that both of this gallery's `AnimationLoop`-driven demos
/// (`structure::demo_anim`, `geometry::demo_geometry_path_follow`) started ticking at page load and ran for the
/// rest of the page's lifetime, animating a hidden panel nobody was looking at.
///
/// This only defers that cost, it does not remove it: once an `AnimationLoop`-driven panel has been visited, its
/// loop is parked in [`LIVE_DEMO_ANIMS`] and keeps ticking for the rest of the page's lifetime even after the user
/// navigates to a different panel — lazy construction fixes "running before anyone asked for it", not "still
/// running once nobody is looking anymore".
///
/// For the two lightweight animations currently in this gallery, the added complexity of a pause/resume lifecycle
/// (e.g. an `activate_panel`/`deactivate_panel` pair, or getting each animation callback to check its own section's
/// `.active` class), is not worth the ffort.
///
/// If the number of animations grows, it would be worth revisiting this design decision.
///
/// Call this from JavaScript each time a panel becomes the active one (see `demo/index.template.html`'s
/// `selectDemo`). It is idempotent — see [`PANEL_STATE_ATTR`] — so calling it again for an already-initialised
/// panel, e.g. navigating back to one visited earlier, is a no-op rather than a duplicate rebuild.
///
/// A demo that fails to build is recorded as `"failed"` rather than retried on a later visit; [`run_panel`] and
/// [`report_panel_error`] are what surface that failure in the gallery itself. A missing or mismatched panel id is
/// a different kind of problem — a catalogue error rather than a demo runtime error — and is caught at server
/// startup instead, before the gallery is ever served (see `demo-server/src/validate.rs` and
/// `demo-server/src/panels.rs`'s `assemble`), so `init_panel` never has to distinguish the two: by the time it
/// runs, the catalogue has already been validated.
#[wasm_bindgen]
pub fn init_panel(panel_id: &str) -> Result<(), JsValue> {
    let e = |err: Error| JsValue::from_str(&err.to_string());
    let document = web_sys::window()
        .and_then(|w| w.document())
        .ok_or_else(|| Error::Dom("no document".into()))
        .map_err(e)?;

    let Some(section) = document.get_element_by_id(panel_id) else { return Ok(()) };
    if section.has_attribute(PANEL_STATE_ATTR) {
        return Ok(());
    }
    let Some(&(_, build, fn_name)) = DEMO_PANELS.iter().find(|(id, ..)| *id == panel_id) else {
        return Ok(());
    };

    let state = if run_panel(panel_id, build) { "ready" } else { "failed" };
    section.set_attribute(PANEL_STATE_ATTR, state).map_err(dom_err).map_err(e)?;

    // Show the Rust source of the function that just built this panel — including when it failed to build; the
    // source is still worth seeing even when the demo itself broke.
    append_source_frame(&document, panel_id, fn_name).map_err(e)?;
    Ok(())
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Runs one demo's build function, catching its error rather than letting it propagate, and reports whether it
/// succeeded so [`init_panel`] can record that as the panel's state. A broken demo is this function's own runtime
/// behaviour, not a missing or mismatched panel — see [`init_panel`]'s doc comment for why those are handled
/// differently.
fn run_panel(panel_id: &str, build: fn() -> Result<(), Error>) -> bool {
    match build() {
        Ok(()) => true,
        Err(err) => {
            report_panel_error(panel_id, &err.to_string());
            false
        },
    }
}

/// Appends a visible failure banner to `panel_id`'s own `<section>`, so a demo that fails to build is immediately
/// obvious in the gallery itself instead of just leaving that panel's canvas blank. This is a development and
/// verification tool; a silently empty panel is exactly the outcome worth avoiding here.
///
/// Silently does nothing if the panel section itself cannot be found — by construction (see [`run_panel`]'s doc
/// comment) that cannot happen through the normal `cargo demo` pipeline, so this mirrors [`append_source_frame`]'s
/// own defensive fallback rather than treating an already-impossible case as fatal.
fn report_panel_error(panel_id: &str, message: &str) {
    let Some(document) = web_sys::window().and_then(|w| w.document()) else {
        return;
    };
    let Some(section) = document.get_element_by_id(panel_id) else { return };
    let Ok(banner) = create_element(&document, "p") else { return };
    banner.set_class_name("demo-error");
    banner.set_text_content(Some(&format!("This demo failed to build: {message}")));
    let _ = section.append_child(&banner);
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Source-code frames
//
// Each panel containing a demo example gets a collapsible frame below its canvas showing the formatted Rust source of
// the function that built it, injected by init_panel the first time that panel is selected. The source TEXT itself is
// embedded at compile time from each sub-module file (via DEMO_SRC/include_str!), so that part genuinely never drifts
// from what is actually running — there is no separate copy of it to keep in sync by hand.
//
// The (panel id -> function) MAPPING that decides which source shows up in which panel is a different matter: it is
// the hand-written `demo_gallery!` invocation above, not something derived automatically. demo-server's `validate`
// step catches a mismatch there at server startup for the normal `cargo demo` pipeline (see
// `demo-server/src/validate.rs`) — but append_source_frame below still fails silently rather than erroring if a panel
// or function genuinely cannot be found, as a fallback for anything run outside that pipeline.
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Builds `<details class="source"><summary>...</summary><pre><code>...</code></pre></details>` and appends it to the
/// panel `<section>`. A missing panel or missing function is skipped rather than treated as an error, so the gallery
/// still renders if `index.html` and this module drift apart.
fn append_source_frame(document: &web_sys::Document, panel_id: &str, fn_name: &str) -> Result<(), Error> {
    let Some(section) = document.get_element_by_id(panel_id) else {
        return Ok(());
    };
    let Some(source) = demo_fn_source(fn_name) else {
        return Ok(());
    };

    let details = create_element(document, "details")?;
    details.set_class_name("source");
    details.set_attribute("open", "").map_err(dom_err)?;

    let summary = create_element(document, "summary")?;
    summary.set_text_content(Some(&format!("Rust source — fn {fn_name}")));
    details.append_child(&summary).map_err(dom_err)?;

    let pre = create_element(document, "pre")?;
    let code = create_element(document, "code")?;
    // `rust_to_html` returns `<span>`-wrapped, HTML-escaped tokens, so angle brackets and ampersands in the code still
    // render verbatim while keywords, strings, etc. are coloured by the CSS classes.
    code.set_inner_html(&highlight::rust_to_html(source));
    pre.append_child(&code).map_err(dom_err)?;
    details.append_child(&pre).map_err(dom_err)?;

    section.append_child(&details).map_err(dom_err)?;
    Ok(())
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Returns the source text of the top-level `fn {name}` item in [`DEMO_SRC`], from the signature line through its
/// closing brace, or `None` if it cannot be located.
///
/// This relies on `rustfmt`'s guarantee that a top-level item's closing brace will always sit in column 0 while every
/// brace nested inside the body (including those inside `format!` strings such as `"translate({x}, {y})"`) will be
/// indented.
///
/// Scanning for the first line that is exactly `}` after the signature therefore finds the function's end without
/// having to parse any string literals or resort to an brace-balancing shenanigans.
fn demo_fn_source(name: &str) -> Option<&'static str> {
    let needle = format!("fn {name}(");
    let hit = DEMO_SRC.find(&needle)?;
    let start = DEMO_SRC[..hit].rfind('\n').map_or(0, |i| i + 1);

    let tail = &DEMO_SRC[hit..];
    let mut from = 0;
    loop {
        let rel = tail[from..].find("\n}")?;
        let close = from + rel + 1; // index of the '}' within `tail`
        let after = close + 1;
        // A genuine top-level close: the '}' stands alone on its line (next byte is a newline or end of file).
        if tail.as_bytes().get(after).is_none_or(|&b| b == b'\n') {
            return Some(&DEMO_SRC[start..hit + after]);
        }
        from = after;
    }
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Creates an element, mapping any DOM failure into [`Error::Dom`].
fn create_element(document: &web_sys::Document, tag: &str) -> Result<web_sys::Element, Error> {
    document.create_element(tag).map_err(dom_err)
}

fn dom_err(e: JsValue) -> Error {
    Error::Dom(format!("{e:?}"))
}

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Shared helper
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/// Appends a small grey caption below an element at horizontal centre `cx`.
fn caption(svg: &SvgRoot, cx: f64, text: &str) -> Result<(), Error> {
    let t = svg.text(Point::new(cx, PAD_Y + BAND - 6.0), text)?;
    let mut attrs = SvgAttrs::new();
    t.attrs(&mut attrs)
        .fill(CAPTION)?
        .apply([("font-size", "11"), ("text-anchor", "middle")])?;
    Ok(())
}

#[cfg(test)]
mod unit_tests;
