//! Static file server for the `svg-dom` feature gallery.
//!
//! Run from the project root with:
//! ```sh
//! cargo demo
//! ```
//!
//! The following steps are performed:
//!
//! 1. `demo-app`'s `demo_gallery!` list and this crate's own panel manifest must agree with each other (see [`validate`])
//! 1. Rebuilds the gallery's `index.html` from `demo/index.template.html` and the various `demo/panels/*.html` files
//!    (see [`panels`])
//! 1. Rebuilds the `svg-dom-demo` crate's wasm package using `wasm-pack build demo-app --target web`
//! 1. Serves the result at <http://127.0.0.1:8080/demo/>
//!
//! The generated `index.html` and the wasm `pkg/` are staged under `target/demo-gallery/` rather than written into the
//! source tree (as earlier versions of this server did) or served straight out of the project root. Concretely:
//!
//! ```text
//! target/demo-gallery/
//! ├── demo/
//! │   ├── index.html      (generated by panels::assemble)
//! │   ├── style.css       (copied from demo/style.css)
//! │   └── view-demo.svg   (copied from demo/view-demo.svg; see structure.rs's <view> demo for what needs it)
//! └── pkg/                 (wasm-pack's output)
//! ```
//!
//! Serving from outside the source tree means:
//!
//! * The checkout stays untouched by `cargo demo` (nothing to accidentally commit and `git status` stays clean)
//! * The static server exposes only the generated gallery, not the repository's own manifests or Rust sources
//! * A failed or interrupted run will not leave a partial artefact sitting in directory monitored by source control
//! * The whole generated gallery is removed by an ordinary `cargo clean`, the same as any other build output
//!
//! The port number can be overridden using the `PORT` environment variable, e.g. `PORT=9000 cargo demo`.
//!
//! The build pipeline itself — resolving staging paths through to a wasm package ready to serve — lives in [`build`],
//! as a `Result`-returning [`build::build_gallery`] rather than something that reports errors and exits on its own.
//! That keeps every "how do we build the gallery" decision testable and reusable independently of Actix, and leaves
//! `main` as the one place that decides what a build failure means for the process.
//!
//! Run with `--prepare-only` (`cargo run -p demo-server -- --prepare-only`) to run [`build::prepare_gallery`] alone
//! — validate the catalogue, assemble `index.html`, copy static assets — and exit, without rebuilding the wasm
//! package or starting the server. This is what lets CI exercise the actual staging pipeline (the same phases
//! `wasm-pack build demo-app ...` on its own bypasses entirely) without paying for a full wasm build every run.
mod build;
mod panels;
mod validate;

use actix_files::Files;
use actix_web::{App, HttpServer, middleware::Logger};
use build::StagePaths;
use std::{path::PathBuf, process};

const DEFAULT_PORT: u16 = 8080;

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    // The demo-server crate lives one level below the project root.
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or_else(|| std::io::Error::other("demo-server must live inside the project"))?
        .to_path_buf();

    // Respects a `CARGO_TARGET_DIR` override the same way `cargo build` itself would, rather than assuming the
    // target directory always sits directly under the project root.
    let target_dir = std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("target"));
    let stage = StagePaths::new(&target_dir);
    let port: u16 = std::env::var("PORT").ok().and_then(|p| p.parse().ok()).unwrap_or(DEFAULT_PORT);

    if std::env::args().any(|arg| arg == "--prepare-only") {
        if let Err(err) = build::prepare_gallery(&root, &stage, port) {
            eprintln!("aborting: {err}");
            process::exit(1);
        }
        println!("gallery staged successfully at {}", stage.demo_dir.display());
        return Ok(());
    }

    // Every build phase — validating the catalogue, assembling index.html, copying static assets, rebuilding the
    // wasm package — runs here, in order, before the server ever starts; a failure at any phase is fatal, so
    // `main` reports it and exits rather than starting Actix in front of an incomplete or stale gallery.
    if let Err(err) = build::build_gallery(&root, &stage, port) {
        eprintln!("aborting: {err}");
        process::exit(1);
    }

    let addr = ("127.0.0.1", port);
    let stage_dir = stage.stage_dir;

    println!("\n  svg-dom-demo running on http://127.0.0.1:{port}/demo/\n");

    HttpServer::new(move || {
        App::new()
            .wrap(Logger::default())
            .service(Files::new("/", stage_dir.clone()).index_file("index.html"))
    })
    .bind(addr)?
    .run()
    .await
}
